HEADER_INPUT_PROPS      = 'rounded outlined dense'
HEADER_TYPESELECT_PROPS = 'rounded outlined dense label="Típus..."'
TOOL_BUTTON_PROPS       = 'flat round color=primary'
WI_BUTTON_PROPS         = 'push dense'
WIHISTORY_BUTTON_PROPS  = 'flat round color=primary dense'